### ISSUE TITLE
Configure Timezone

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#104]
Taken from https://github.com/GFUCABAM/statler/pull/102/files. Code handling dates has since been moved to the Review model.

```
64  +        # TODO: This resulted in a warning when .toDao().save() was  
65  +        # called on the object:  
66  +        # C:\Program Files\Python34\lib\site-packages\django\db\models\fields\__init__.py:  
67  +        # 1474: RuntimeWarning: DateTimeField ReviewDAO.timestamp received a naive datetim  
68  +        # e (2015-11-10 05:39:55.612406) while time zone support is active.  
69  +        # RuntimeWarning)  
```

**Comment by bencdelaney** [comment]
Also, it looks like a test is failing:

```
Error
Traceback (most recent call last):
  File "...\statler_api\tests\test_reviews.py", line 36, in testCreateFromText
    self.assertGreaterEqual(theReview.timestamp, startTimeStamp)
  File "C:\Python\Python33\lib\unittest\case.py", line 1042, in assertGreaterEqual
    if not a >= b:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by mnijmeh11** [comment]
I am trying to find the fix. I might have found a possible solution 

-----Original Message-----

**Comment by mnijmeh11** [comment]
from django.test import TestCase
from statler_api.models import Review, Play
from django.utils import timezone

from statler_api.tests.test_plays import PlayTestHelper

class ReviewTestCase(TestCase):

```
def testGetApiFields(self):
    review = Review()
    review.play = Play()
    review.timestamp = datetime.today()
    review.text = "foo"

    apiDict = review.getApiFields()

    self.assertEqual(apiDict, {"text": "foo", "timestamp": datetime.today().isoformat()})

def testCreateFromText(self):

    startTimeStamp = datetime.now()

    # Set up a play to reference.
    play = PlayTestHelper.makePlay(PlayTestHelper.Play1Vals)
    play.save()

    theReview = Review.createFromText("The play was foo.", play.url_title)

    self.assertEqual(theReview.text, "The play was foo.")
    self.assertIsNotNone(theReview.rating)
    self.assertEqual(theReview.play, play)

    # Check the timestamp against some bounds.
    endTimeStamp = datetime.now()
    self.assertGreaterEqual(theReview.timestamp, startTimeStamp)
    self.assertLessEqual(theReview.timestamp, endTimeStamp)
```

**Comment by mnijmeh11** [comment]
https://docs.djangoproject.com/en/1.8/topics/i18n/timezones/

**Comment by bencdelaney** [comment]
It looks like you're on track. Is making necessary code changes on track? Do you have any questions?

**Comment by mnijmeh11** [comment]
I made it already 

-----Original Message-----

**Comment by bencdelaney** [comment]
Cool. Is the code accessible somewhere? In a branch, maybe?

**Comment by mnijmeh11** [comment]
I pasted it into the issue and updated my branch and pasted the URL with the explanation of the error into the issue

-----Original Message-----

**Comment by mnijmeh11** [comment]
0
down vote
To get a set of all valid timezone names (ids) from the tz database, you could use pytz module in Python:

> > > import pytz # $ pip install pytz
> > > pytz.all_timezones_set
> > > LazySet({'Africa/Abidjan',
> > >          'Africa/Accra',
> > >          'Africa/Addis_Ababa',
> > >          'Africa/Algiers',
> > >          'Africa/Asmara',
> > >          'Africa/Asmera',
> > >          ...
> > >          'UTC',
> > >          'Universal',
> > >          'W-SU',
> > >          'WET',
> > >          'Zulu'})

**Comment by mnijmeh11** [comment]
Code¶

The first step is to add USE_TZ = True to your settings file and install pytz (if possible). At this point, things should mostly work. If you create naive datetime objects in your code, Django makes them aware when necessary.

However, these conversions may fail around DST transitions, which means you aren’t getting the full benefits of time zone support yet. Also, you’re likely to run into a few problems because it’s impossible to compare a naive datetime with an aware datetime. Since Django now gives you aware datetimes, you’ll get exceptions wherever you compare a datetime that comes from a model or a form with a naive datetime that you’ve created in your code.

So the second step is to refactor your code wherever you instantiate datetime objects to make them aware. This can be done incrementally. django.utils.timezone defines some handy helpers for compatibility code: now(), is_aware(), is_naive(), make_aware(), and make_naive().

Finally, in order to help you locate code that needs upgrading, Django raises a warning when you attempt to save a naive datetime to the database:

**Comment by mnijmeh11** [comment]
Keep it open to refer to it incase you need to refer to it
