### ISSUE TITLE
Create "about" content

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#151]
- About Ten! Ten! Ten!? (Let's talk to theatre)
- About us/the project/statler/tententenreviews.com/whatever

**Comment by bencdelaney** [comment]
About _Ten! Ten! Ten!_ Content, directly from Rhett:

> Ten! Ten! Ten! is the final directing project for THEA 370: Directing of the Stage. Ten! Ten! Ten! has been a theatre tradition at George Fox University for the past 15 years. For more information about GFU Theatre go to theatre.georgefox.edu.

**Comment by areinhardt14** [comment]
Is this a decent "about us"?

Who Are We?
tententenreviews.com is the product of a semester-long project for GFU's Software Engineering class. Our team had to create a system that would rank products like movies or plays based on a sentiment analysis of user reviews, instead of a numbered ranking system like "stars." We thought it would be a great learning experience (and a fun challenge!) for us to make the system a real product used by real people, so we contacted the Theater Department to see if they would like to be our client. For some reason, they did, and we're thrilled to present to you a site specially designed for Ten! Ten! Ten! reviews.

**Comment by chaneberg** [comment]
I added an About page

![capture](https://cloud.githubusercontent.com/assets/12008786/11587012/7e4402de-9a2b-11e5-8db4-f816b35a2215.PNG)

let me know if the content looks good or needs changes.
