### ISSUE TITLE
Redirect www. subdomain to site

### ISSUE THREAD

**Issue by chaneberg** [GFUCABAM/statler#166]

**Comment by mnijmeh11** [comment]
24 to 48 hour refreash time...sorry 1and1 is slow....

**Comment by mnijmeh11** [comment]
Error 404 - Web app not found.

The web app you have attempted to reach is not available in this Microsoft Azure App Service region. This could be due to one of several reasons:
1. The web app owner has registered a custom domain to point to the Microsoft Azure App Service, but has not yet configured Azure to recognize it. Click here to read more.

**Comment by chaneberg** [comment]
Hey @B3nD3lan3y, I guess the message "The web app owner has registered a custom domain to point to the Microsoft Azure App Service, but has not yet configured Azure to recognize it" means the DNS thing is working, but Azure needs to recognize www.tententenreviews.com

**Comment by mnijmeh11** [comment]
I am waiting for Ben to fix it on his end

-----Original Message-----

**Comment by mnijmeh11** [comment]
created cname and checked it out recently....

**Comment by mnijmeh11** [comment]
fixed.....
