### ISSUE TITLE
Test 0.1 /api/plays/{url-title} endpoint

### ISSUE THREAD

**Issue by bencdelaney** [GFUCABAM/statler#21]
The following url-titles should return a 200 with JSON conent:
- play-1
- play-2
- play-3

All others should return a 404 with no content.

**Comment by mnijmeh11** [comment]
SoapUI. The Swiss-Army Knife of Testing.
SoapUI is a free and open source cross-platform Functional Testing solution. With an easy-to-use graphical interface, and enterprise-class features, SoapUI allows you to easily and rapidly create and execute automated functional, regression, compliance, and load tests. In a single test environment, SoapUI provides complete test coverage and supports all the standard protocols and technologies. There are simply no limits to what you can do with your tests. Meet SoapUI, the world's most complete testing tool!

**Comment by mnijmeh11** [comment]
When we are going to start test and building I have several on-line apps and pc based tools to help us with testing as we build test and deploy...

**Comment by chaneberg** [comment]
The URL <code>/api/play-list/</code> now serves json, and is ready to test (if testing can be done with the site only on localhost)

**Comment by mnijmeh11** [comment]
http://resttesttest.com/ I have been not liking the soapui because it seem to be really hard to get to work correctly..
but http://resttesttest.com/ does simple testing and requesting results displayed

**Comment by mnijmeh11** [comment]
Supercharge your API workflow with Postman! Build, test, and document your APIs faster. More than a million developers already do.…
Supercharge your API workflow with Postman!

Build, test, and document your APIs faster. More than a million developers already do.

The idea for Postman arose while the founders were working together, and were frustrated with the existing tools for testing APIs. They felt there had to be a better language for developers to communicate about APIs. This led to the creation of Postman. Postman helps you build, test, and document APIs faster. 

Postman features include:
- History of sent requests
- Create requests quickly
- Replay and organize
- Switch context quickly
- Built-in authentication helpers
- Customize with scripts
- Robust testing framework
- Automate collections

Apart from this, you can also upgrade with Jetpacks to unlock the collection runner and test editor within Postman. Only $9.99 for a single license. Free upgrades for life.

All this is available in an intuitive user interface that would make testing APIs effortless.

Note on Permissions

The “Your data on all websites” permission is required to send a request to a domain. It's not used for anything else. It's not a new permission and Postman has required it since it was launched.

View the complete Postman EULA at: https://www.getpostman.com/licenses/postman_base_app

**Comment by mnijmeh11** [comment]
going to setup a wiki on how to test each part with chrome plugins so that everyone can do it with their broswer
