### ISSUE TITLE
Link to Sentiment API

### ISSUE THREAD

**Issue by areinhardt14** [GFUCABAM/statler#45]
Enable the API to make a JSON request to the https://github.com/vivekn/sentiment API and store what it sends back.

**Comment by mnijmeh11** [comment]
http://www.cs.jhu.edu/~mdredze/datasets/sentiment/
http://nevonprojects.com/sentiment-based-movie-rating-system/

**Comment by mnijmeh11** [comment]
Advantages
•Allows for automated movie rating system.
•False rating cannot be entered since system calculates based on user comments.
•It removes human errors that commonly occur during manual analysis.
•The system provides an unbiased result.
•Thus the system excludes human efforts and saves time and resources.

Disadvantages
•The system must be given proper inputs otherwise system can produce wrong results.
•The system needs to be hosted on cloud to receive and process country wide results.

Related Projects:
•Sentiment Analysis for Product Rating
•Opinion Mining For Comment Sentiment Analysis
•Opinion Mining For Hotel Rating Through Reviews
•Web Content Trust Rating Prediction Using Evidence Theory
•Opinion Mining For Automated Restaurant Reviews Rating

**Comment by mnijmeh11** [comment]
http://nevonprojects.com/video-tutorials-demo/

**Comment by mnijmeh11** [comment]
https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html

**Comment by mnijmeh11** [comment]
https://groups.google.com/forum/#!forum/sentiment140

**Comment by mnijmeh11** [comment]
http://tententenreviews.com/index.htm
I setup a basic ok to kill website to show we are working on the site

**Comment by bencdelaney** [comment]
Let's put all our external api access code in new file in statler_api.

**Comment by bencdelaney** [comment]
I wrote a couple unit tests, and opened #93 to add them to the Anastasia branch.

It looks like the code currently in that branch may be trying to use the HtttpRequest.POST attribute incorrectly. A little poking around made me suspect we need to use something other than Django to construct the request (urllib2?). Let me know if you have any questions regarding making the request or running the unit tests.

**Comment by bencdelaney** [comment]
It looks like our best option is probably [Requests](http://docs.python-requests.org/en/latest/). To develop with it, we'll need to install it on our development machines. `pip install Requests`  should do the trick. If pip complains about access to your python installation, `pip install --user Requests` should work as well. If pip isn't working from the command line PyCharm has can install packages as well (It's a little unintuitive, so Google it).

**Comment by bencdelaney** [comment]
Changes merged in #107
